version: 2
models:
  - name: int_train_full
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - date
              - store_number
              - family          
    columns:
      - name: date
        tests:
          - not_null
      - name: store_number
        tests:
          - not_null
      - name: family
        tests:
          - not_null
      - name: sales
        tests:
          - not_null
      - name: onpromotion
        tests:
          - not_null

  - name: int_work_day
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - date
              - store_number
              - family
    columns:
      - name: date
        tests:
          - not_null
      - name: store_number
        tests:
          - not_null
      - name: family
        tests:
          - not_null
      - name: work_day
        tests:
          - not_null

  - name: int_calendar
    columns:
      - name: date
        tests:
          - unique
          - not_null
      - name: week_day
        tests:
          - accepted_values:
              arguments:
                values: ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
  - name: int_oil
    columns:
      - name: date
        tests:
          - unique
          - not_null
      - name: oil_price_filled
        tests:
          - not_null

  - name: int_lags
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - date
              - store_number
              - family
    columns:
      - name: date
        tests:
          - not_null
      - name: store_number
        tests:
          - not_null
      - name: family
        tests:
          - not_null
      - name: avg_7
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
      - name: avg_28
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0